version: '3'
services:
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - 80:80
    volumes:
      - ./docker/supervisor.conf:/etc/supervisor/conf.d/supervisor.conf
      - ./docker/nginx.conf:/etc/nginx/sites-enabled/nginx.conf
      - ./logs:/var/www/logs
      - ./src:/var/www/html

  mysql:
    image: mariadb:10.3.2
    volumes:
      - ./docker/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: platform
    ports:
      - 3306:3306